//THIS FILE IS GENERATED BY REG_BUILDER
`ifndef DELAY
    `define DELAY #0.1
`endif


module CDC 
(
    input i_cfg_clk
    ,input i_cfg_rst_n
    
    ,input i_vl_rx_1_clk
    ,input i_vl_rx_1_rst_n

    ,input i_vl_rx_3_clk
    ,input i_vl_rx_3_rst_n

    ,input i_vl_rx_0_clk
    ,input i_vl_rx_0_rst_n

    ,input i_vl_rx_2_clk
    ,input i_vl_rx_2_rst_n

    ,input [0:0] i_vl_rx_0_comma_aligned_l0
    ,output [0:0] o_csr_comma_aligned_l0

    ,input [0:0] i_vl_rx_1_comma_aligned_l1
    ,output [0:0] o_csr_comma_aligned_l1

    ,input [0:0] i_vl_rx_2_comma_aligned_l2
    ,output [0:0] o_csr_comma_aligned_l2

    ,input [0:0] i_vl_rx_3_comma_aligned_l3
    ,output [0:0] o_csr_comma_aligned_l3

    ,input [0:0] i_csr_disp_err_l0_clr
    ,output [0:0] o_vl_rx_0_disp_err_l0_clr

    ,input [0:0] i_vl_rx_0_disp_err_l0
    ,output [0:0] o_csr_disp_err_l0

    ,input [0:0] i_csr_disp_err_l1_clr
    ,output [0:0] o_vl_rx_1_disp_err_l1_clr

    ,input [0:0] i_vl_rx_1_disp_err_l1
    ,output [0:0] o_csr_disp_err_l1

    ,input [0:0] i_csr_disp_err_l2_clr
    ,output [0:0] o_vl_rx_2_disp_err_l2_clr

    ,input [0:0] i_vl_rx_2_disp_err_l2
    ,output [0:0] o_csr_disp_err_l2

    ,input [0:0] i_csr_disp_err_l3_clr
    ,output [0:0] o_vl_rx_3_disp_err_l3_clr

    ,input [0:0] i_vl_rx_3_disp_err_l3
    ,output [0:0] o_csr_disp_err_l3

    ,input [0:0] i_csr_rxld_overflow_l0_clr
    ,output [0:0] o_vl_rx_0_rxld_overflow_l0_clr

    ,input [0:0] i_vl_rx_0_rxld_overflow_l0
    ,output [0:0] o_csr_rxld_overflow_l0

    ,input [0:0] i_csr_rxld_overflow_l1_clr
    ,output [0:0] o_vl_rx_1_rxld_overflow_l1_clr

    ,input [0:0] i_vl_rx_1_rxld_overflow_l1
    ,output [0:0] o_csr_rxld_overflow_l1

    ,input [0:0] i_csr_rxld_overflow_l2_clr
    ,output [0:0] o_vl_rx_2_rxld_overflow_l2_clr

    ,input [0:0] i_vl_rx_2_rxld_overflow_l2
    ,output [0:0] o_csr_rxld_overflow_l2

    ,input [0:0] i_csr_rxld_overflow_l3_clr
    ,output [0:0] o_vl_rx_3_rxld_overflow_l3_clr

    ,input [0:0] i_vl_rx_3_rxld_overflow_l3
    ,output [0:0] o_csr_rxld_overflow_l3

    ,input [0:0] i_csr_rxld_underflow_l0_clr
    ,output [0:0] o_vl_rx_0_rxld_underflow_l0_clr

    ,input [0:0] i_vl_rx_0_rxld_underflow_l0
    ,output [0:0] o_csr_rxld_underflow_l0

    ,input [0:0] i_csr_rxld_underflow_l1_clr
    ,output [0:0] o_vl_rx_0_rxld_underflow_l1_clr

    ,input [0:0] i_vl_rx_0_rxld_underflow_l1
    ,output [0:0] o_csr_rxld_underflow_l1

    ,input [0:0] i_csr_rxld_underflow_l2_clr
    ,output [0:0] o_vl_rx_0_rxld_underflow_l2_clr

    ,input [0:0] i_vl_rx_0_rxld_underflow_l2
    ,output [0:0] o_csr_rxld_underflow_l2

    ,input [0:0] i_csr_rxld_underflow_l3_clr
    ,output [0:0] o_vl_rx_0_rxld_underflow_l3_clr

    ,input [0:0] i_vl_rx_0_rxld_underflow_l3
    ,output [0:0] o_csr_rxld_underflow_l3

    ,input [0:0] i_vl_rx_0_rxld_aligned
    ,output [0:0] o_csr_rxld_aligned

    ,input [0:0] i_csr_rs_fail_l0_clr
    ,output [0:0] o_vl_rx_0_rs_fail_l0_clr

    ,input [0:0] i_vl_rx_0_rs_fail_l0
    ,output [0:0] o_csr_rs_fail_l0

    ,input [0:0] i_csr_rs_fail_l1_clr
    ,output [0:0] o_vl_rx_0_rs_fail_l1_clr

    ,input [0:0] i_vl_rx_0_rs_fail_l1
    ,output [0:0] o_csr_rs_fail_l1

    ,input [0:0] i_csr_rs_fail_l2_clr
    ,output [0:0] o_vl_rx_0_rs_fail_l2_clr

    ,input [0:0] i_vl_rx_0_rs_fail_l2
    ,output [0:0] o_csr_rs_fail_l2

    ,input [0:0] i_csr_rs_fail_l3_clr
    ,output [0:0] o_vl_rx_0_rs_fail_l3_clr

    ,input [0:0] i_vl_rx_0_rs_fail_l3
    ,output [0:0] o_csr_rs_fail_l3

    ,input [0:0] i_csr_rs_found_l0_clr
    ,output [0:0] o_vl_rx_0_rs_found_l0_clr

    ,input [0:0] i_vl_rx_0_rs_found_l0
    ,output [0:0] o_csr_rs_found_l0

    ,input [0:0] i_csr_rs_found_l1_clr
    ,output [0:0] o_vl_rx_0_rs_found_l1_clr

    ,input [0:0] i_vl_rx_0_rs_found_l1
    ,output [0:0] o_csr_rs_found_l1

    ,input [0:0] i_csr_rs_found_l2_clr
    ,output [0:0] o_vl_rx_0_rs_found_l2_clr

    ,input [0:0] i_vl_rx_0_rs_found_l2
    ,output [0:0] o_csr_rs_found_l2

    ,input [0:0] i_csr_rs_found_l3_clr
    ,output [0:0] o_vl_rx_0_rs_found_l3_clr

    ,input [0:0] i_vl_rx_0_rs_found_l3
    ,output [0:0] o_csr_rs_found_l3

    ,input [0:0] i_csr_rs_fail_cnt_l0_clr
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l0_clr

    ,input [15:0] i_vl_rx_0_rs_fail_cnt_l0
    ,output [15:0] o_csr_rs_fail_cnt_l0

    ,input [0:0] i_csr_rs_fail_cnt_l1_clr
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l1_clr

    ,input [15:0] i_vl_rx_0_rs_fail_cnt_l1
    ,output [15:0] o_csr_rs_fail_cnt_l1

    ,input [0:0] i_csr_rs_fail_cnt_l2_clr
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l2_clr

    ,input [15:0] i_vl_rx_0_rs_fail_cnt_l2
    ,output [15:0] o_csr_rs_fail_cnt_l2

    ,input [0:0] i_csr_rs_fail_cnt_l3_clr
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l3_clr

    ,input [15:0] i_vl_rx_0_rs_fail_cnt_l3
    ,output [15:0] o_csr_rs_fail_cnt_l3

    ,input [0:0] i_csr_rs_err_num_cnt_l0_clr
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l0_clr

    ,input [15:0] i_vl_rx_0_rs_err_num_cnt_l0
    ,output [15:0] o_csr_rs_err_num_cnt_l0

    ,input [0:0] i_csr_rs_err_num_cnt_l1_clr
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l1_clr

    ,input [15:0] i_vl_rx_0_rs_err_num_cnt_l1
    ,output [15:0] o_csr_rs_err_num_cnt_l1

    ,input [0:0] i_csr_rs_err_num_cnt_l2_clr
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l2_clr

    ,input [15:0] i_vl_rx_0_rs_err_num_cnt_l2
    ,output [15:0] o_csr_rs_err_num_cnt_l2

    ,input [0:0] i_csr_rs_err_num_cnt_l3_clr
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l3_clr

    ,input [15:0] i_vl_rx_0_rs_err_num_cnt_l3
    ,output [15:0] o_csr_rs_err_num_cnt_l3

    ,input [0:0] i_vl_rx_0_rxpol_done_l0
    ,output [0:0] o_csr_rxpol_done_l0

    ,input [0:0] i_vl_rx_1_rxpol_done_l1
    ,output [0:0] o_csr_rxpol_done_l1

    ,input [0:0] i_vl_rx_2_rxpol_done_l2
    ,output [0:0] o_csr_rxpol_done_l2

    ,input [0:0] i_vl_rx_3_rxpol_done_l3
    ,output [0:0] o_csr_rxpol_done_l3

    ,input [0:0] i_vl_rx_0_rxpol_status_l0
    ,output [0:0] o_csr_rxpol_status_l0

    ,input [0:0] i_vl_rx_1_rxpol_status_l1
    ,output [0:0] o_csr_rxpol_status_l1

    ,input [0:0] i_vl_rx_2_rxpol_status_l2
    ,output [0:0] o_csr_rxpol_status_l2

    ,input [0:0] i_vl_rx_3_rxpol_status_l3
    ,output [0:0] o_csr_rxpol_status_l3

    ,input [0:0] i_csr_mci_val
    ,output [0:0] o_vl_rx_0_mci_val

    ,input [0:0] i_csr_mci_rdwn
    ,output [0:0] o_vl_rx_0_mci_rdwn

    ,input [0:0] i_vl_rx_0_mci_ack
    ,output [0:0] o_csr_mci_ack

    ,input [0:0] i_csr_mci_owner
    ,output [0:0] o_vl_rx_0_mci_owner



);

    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_COMMA_ALIGNED_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_comma_aligned_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_comma_aligned_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_comma_aligned_l0  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_COMMA_ALIGNED_L1)
    )
    m_ccd_vl_rx_1_clk2cfg_clk_vl_rx_1_comma_aligned_l1(
        .i_s_rst_n      (i_vl_rx_1_rst_n ),
        .i_src_clk      (i_vl_rx_1_clk ),
        .i_s_din        (i_vl_rx_1_comma_aligned_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_comma_aligned_l1  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_COMMA_ALIGNED_L2)
    )
    m_ccd_vl_rx_2_clk2cfg_clk_vl_rx_2_comma_aligned_l2(
        .i_s_rst_n      (i_vl_rx_2_rst_n ),
        .i_src_clk      (i_vl_rx_2_clk ),
        .i_s_din        (i_vl_rx_2_comma_aligned_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_comma_aligned_l2  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_COMMA_ALIGNED_L3)
    )
    m_ccd_vl_rx_3_clk2cfg_clk_vl_rx_3_comma_aligned_l3(
        .i_s_rst_n      (i_vl_rx_3_rst_n ),
        .i_src_clk      (i_vl_rx_3_clk ),
        .i_s_din        (i_vl_rx_3_comma_aligned_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_comma_aligned_l3  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_disp_err_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_disp_err_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_disp_err_l0_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_DISP_ERR_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_disp_err_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_disp_err_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_disp_err_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_1_clk_csr_disp_err_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_disp_err_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_1_rst_n ),
        .i_dest_clk     (i_vl_rx_1_clk),
        .o_d_dout       (o_vl_rx_1_disp_err_l1_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_DISP_ERR_L1)
    )
    m_ccd_vl_rx_1_clk2cfg_clk_vl_rx_1_disp_err_l1(
        .i_s_rst_n      (i_vl_rx_1_rst_n ),
        .i_src_clk      (i_vl_rx_1_clk ),
        .i_s_din        (i_vl_rx_1_disp_err_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_disp_err_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_2_clk_csr_disp_err_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_disp_err_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_2_rst_n ),
        .i_dest_clk     (i_vl_rx_2_clk),
        .o_d_dout       (o_vl_rx_2_disp_err_l2_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_DISP_ERR_L2)
    )
    m_ccd_vl_rx_2_clk2cfg_clk_vl_rx_2_disp_err_l2(
        .i_s_rst_n      (i_vl_rx_2_rst_n ),
        .i_src_clk      (i_vl_rx_2_clk ),
        .i_s_din        (i_vl_rx_2_disp_err_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_disp_err_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_3_clk_csr_disp_err_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_disp_err_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_3_rst_n ),
        .i_dest_clk     (i_vl_rx_3_clk),
        .o_d_dout       (o_vl_rx_3_disp_err_l3_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_DISP_ERR_L3)
    )
    m_ccd_vl_rx_3_clk2cfg_clk_vl_rx_3_disp_err_l3(
        .i_s_rst_n      (i_vl_rx_3_rst_n ),
        .i_src_clk      (i_vl_rx_3_clk ),
        .i_s_din        (i_vl_rx_3_disp_err_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_disp_err_l3  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rxld_overflow_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_overflow_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rxld_overflow_l0_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_OVERFLOW_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxld_overflow_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxld_overflow_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_overflow_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_1_clk_csr_rxld_overflow_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_overflow_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_1_rst_n ),
        .i_dest_clk     (i_vl_rx_1_clk),
        .o_d_dout       (o_vl_rx_1_rxld_overflow_l1_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_OVERFLOW_L1)
    )
    m_ccd_vl_rx_1_clk2cfg_clk_vl_rx_1_rxld_overflow_l1(
        .i_s_rst_n      (i_vl_rx_1_rst_n ),
        .i_src_clk      (i_vl_rx_1_clk ),
        .i_s_din        (i_vl_rx_1_rxld_overflow_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_overflow_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_2_clk_csr_rxld_overflow_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_overflow_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_2_rst_n ),
        .i_dest_clk     (i_vl_rx_2_clk),
        .o_d_dout       (o_vl_rx_2_rxld_overflow_l2_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_OVERFLOW_L2)
    )
    m_ccd_vl_rx_2_clk2cfg_clk_vl_rx_2_rxld_overflow_l2(
        .i_s_rst_n      (i_vl_rx_2_rst_n ),
        .i_src_clk      (i_vl_rx_2_clk ),
        .i_s_din        (i_vl_rx_2_rxld_overflow_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_overflow_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_3_clk_csr_rxld_overflow_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_overflow_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_3_rst_n ),
        .i_dest_clk     (i_vl_rx_3_clk),
        .o_d_dout       (o_vl_rx_3_rxld_overflow_l3_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_OVERFLOW_L3)
    )
    m_ccd_vl_rx_3_clk2cfg_clk_vl_rx_3_rxld_overflow_l3(
        .i_s_rst_n      (i_vl_rx_3_rst_n ),
        .i_src_clk      (i_vl_rx_3_clk ),
        .i_s_din        (i_vl_rx_3_rxld_overflow_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_overflow_l3  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rxld_underflow_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_underflow_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rxld_underflow_l0_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_UNDERFLOW_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxld_underflow_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxld_underflow_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_underflow_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rxld_underflow_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_underflow_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rxld_underflow_l1_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_UNDERFLOW_L1)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxld_underflow_l1(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxld_underflow_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_underflow_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rxld_underflow_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_underflow_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rxld_underflow_l2_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_UNDERFLOW_L2)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxld_underflow_l2(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxld_underflow_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_underflow_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rxld_underflow_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rxld_underflow_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rxld_underflow_l3_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_UNDERFLOW_L3)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxld_underflow_l3(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxld_underflow_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_underflow_l3  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXLD_ALIGNED)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxld_aligned(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxld_aligned   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxld_aligned  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_l0_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FAIL_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_l1_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FAIL_L1)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_l1(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_l2_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FAIL_L2)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_l2(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_l3_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FAIL_L3)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_l3(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_l3  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_found_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_found_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_found_l0_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FOUND_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_found_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_found_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_found_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_found_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_found_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_found_l1_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FOUND_L1)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_found_l1(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_found_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_found_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_found_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_found_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_found_l2_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FOUND_L2)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_found_l2(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_found_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_found_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_found_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_found_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_found_l3_clr  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RS_FOUND_L3)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_found_l3(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_found_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_found_l3  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_cnt_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_cnt_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_cnt_l0_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_FAIL_CNT_L0)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_cnt_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_cnt_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_cnt_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_cnt_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_cnt_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_cnt_l1_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_FAIL_CNT_L1)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_cnt_l1(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_cnt_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_cnt_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_cnt_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_cnt_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_cnt_l2_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_FAIL_CNT_L2)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_cnt_l2(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_cnt_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_cnt_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_fail_cnt_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_fail_cnt_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_fail_cnt_l3_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_FAIL_CNT_L3)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_fail_cnt_l3(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_fail_cnt_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_fail_cnt_l3  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_err_num_cnt_l0_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_err_num_cnt_l0_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_err_num_cnt_l0_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_ERR_NUM_CNT_L0)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_err_num_cnt_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_err_num_cnt_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_err_num_cnt_l0  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_err_num_cnt_l1_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_err_num_cnt_l1_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_err_num_cnt_l1_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_ERR_NUM_CNT_L1)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_err_num_cnt_l1(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_err_num_cnt_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_err_num_cnt_l1  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_err_num_cnt_l2_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_err_num_cnt_l2_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_err_num_cnt_l2_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_ERR_NUM_CNT_L2)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_err_num_cnt_l2(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_err_num_cnt_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_err_num_cnt_l2  )
    ); 
        
    CLKCROSSPLS m_ccs_cfg_clk2vl_rx_0_clk_csr_rs_err_num_cnt_l3_clr(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_rs_err_num_cnt_l3_clr   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_rs_err_num_cnt_l3_clr  )
    ); 
        
    CLKCROSSBUS # (
        .DATA_WIDTH(16) 
        //.OUT_RESET_VALUE(`DEFVAL_RS_ERR_NUM_CNT_L3)
    )
    m_ccb_vl_rx_0_clk2cfg_clk_vl_rx_0_rs_err_num_cnt_l3(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rs_err_num_cnt_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rs_err_num_cnt_l3  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_DONE_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxpol_done_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxpol_done_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_done_l0  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_DONE_L1)
    )
    m_ccd_vl_rx_1_clk2cfg_clk_vl_rx_1_rxpol_done_l1(
        .i_s_rst_n      (i_vl_rx_1_rst_n ),
        .i_src_clk      (i_vl_rx_1_clk ),
        .i_s_din        (i_vl_rx_1_rxpol_done_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_done_l1  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_DONE_L2)
    )
    m_ccd_vl_rx_2_clk2cfg_clk_vl_rx_2_rxpol_done_l2(
        .i_s_rst_n      (i_vl_rx_2_rst_n ),
        .i_src_clk      (i_vl_rx_2_clk ),
        .i_s_din        (i_vl_rx_2_rxpol_done_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_done_l2  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_DONE_L3)
    )
    m_ccd_vl_rx_3_clk2cfg_clk_vl_rx_3_rxpol_done_l3(
        .i_s_rst_n      (i_vl_rx_3_rst_n ),
        .i_src_clk      (i_vl_rx_3_clk ),
        .i_s_din        (i_vl_rx_3_rxpol_done_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_done_l3  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_STATUS_L0)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_rxpol_status_l0(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_rxpol_status_l0   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_status_l0  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_STATUS_L1)
    )
    m_ccd_vl_rx_1_clk2cfg_clk_vl_rx_1_rxpol_status_l1(
        .i_s_rst_n      (i_vl_rx_1_rst_n ),
        .i_src_clk      (i_vl_rx_1_clk ),
        .i_s_din        (i_vl_rx_1_rxpol_status_l1   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_status_l1  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_STATUS_L2)
    )
    m_ccd_vl_rx_2_clk2cfg_clk_vl_rx_2_rxpol_status_l2(
        .i_s_rst_n      (i_vl_rx_2_rst_n ),
        .i_src_clk      (i_vl_rx_2_clk ),
        .i_s_din        (i_vl_rx_2_rxpol_status_l2   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_status_l2  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_RXPOL_STATUS_L3)
    )
    m_ccd_vl_rx_3_clk2cfg_clk_vl_rx_3_rxpol_status_l3(
        .i_s_rst_n      (i_vl_rx_3_rst_n ),
        .i_src_clk      (i_vl_rx_3_clk ),
        .i_s_din        (i_vl_rx_3_rxpol_status_l3   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_rxpol_status_l3  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_MCI_VAL)
    )
    m_ccd_cfg_clk2vl_rx_0_clk_csr_mci_val(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_mci_val   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_mci_val  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_MCI_RDWN)
    )
    m_ccd_cfg_clk2vl_rx_0_clk_csr_mci_rdwn(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_mci_rdwn   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_mci_rdwn  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_MCI_ACK)
    )
    m_ccd_vl_rx_0_clk2cfg_clk_vl_rx_0_mci_ack(
        .i_s_rst_n      (i_vl_rx_0_rst_n ),
        .i_src_clk      (i_vl_rx_0_clk ),
        .i_s_din        (i_vl_rx_0_mci_ack   ),
        .i_d_rst_n      (i_cfg_rst_n ),
        .i_dest_clk     (i_cfg_clk),
        .o_d_dout       (o_csr_mci_ack  )
    ); 
        
    CLKCROSSDFF # (
        .DATA_WIDTH(1)
        //.RESET_VALUE(`DEFVAL_MCI_OWNER)
    )
    m_ccd_cfg_clk2vl_rx_0_clk_csr_mci_owner(
        .i_s_rst_n      (i_cfg_rst_n ),
        .i_src_clk      (i_cfg_clk ),
        .i_s_din        (i_csr_mci_owner   ),
        .i_d_rst_n      (i_vl_rx_0_rst_n ),
        .i_dest_clk     (i_vl_rx_0_clk),
        .o_d_dout       (o_vl_rx_0_mci_owner  )
    ); 
        

    
    
endmodule
    
    
    
