//THIS FILE IS GENERATED BY REG_BUILDER
`ifndef DELAY
    `define DELAY #0.1
`endif


module CFG #(
    parameter AWIDTH = 16,
    parameter DWIDTH = 16
)
(
    input                       i_cfg_clk                                     
    ,input                      i_cfg_rst_n                                  
    ,input       [AWIDTH-1:0]   i_cfg_addr                   
    ,input                      i_cfg_wr_en                  
    ,input       [DWIDTH-1:0]   i_cfg_wr_data                
    ,input                      i_cfg_rd_en                  
    ,output      [DWIDTH-1:0]   o_cfg_rd_data                
    ,input i_vl_rx_1_clk
    ,input i_vl_rx_1_rst_n

    ,input i_vl_rx_3_clk
    ,input i_vl_rx_3_rst_n

    ,input i_vl_rx_0_clk
    ,input i_vl_rx_0_rst_n

    ,input i_vl_rx_2_clk
    ,input i_vl_rx_2_rst_n

    ,output [0:0] o_csr_soft_pcs_rst
    ,output [0:0] o_csr_soft_tx_rst
    ,output [0:0] o_csr_soft_rx_rst
    ,output [15:0] o_csr_rw_scratch
    ,output [0:0] o_csr_tx_x1_mode_en
    ,output [0:0] o_csr_rx_x1_mode_en
    ,output [0:0] o_csr_tx_rs_en
    ,output [0:0] o_csr_rx_rs_en
    ,input  [0:0] i_vl_rx_0_comma_aligned_l0
    ,input  [0:0] i_vl_rx_1_comma_aligned_l1
    ,input  [0:0] i_vl_rx_2_comma_aligned_l2
    ,input  [0:0] i_vl_rx_3_comma_aligned_l3
    ,output [0:0] o_vl_rx_0_disp_err_l0_clr
    ,input  [0:0] i_vl_rx_0_disp_err_l0
    ,output [0:0] o_vl_rx_1_disp_err_l1_clr
    ,input  [0:0] i_vl_rx_1_disp_err_l1
    ,output [0:0] o_vl_rx_2_disp_err_l2_clr
    ,input  [0:0] i_vl_rx_2_disp_err_l2
    ,output [0:0] o_vl_rx_3_disp_err_l3_clr
    ,input  [0:0] i_vl_rx_3_disp_err_l3
    ,output [4:0] o_csr_rxld_half_thres
    ,output [7:0] o_csr_rxld_align_det_thres
    ,output [7:0] o_csr_rxld_align_los_thres
    ,output [0:0] o_vl_rx_0_rxld_overflow_l0_clr
    ,input  [0:0] i_vl_rx_0_rxld_overflow_l0
    ,output [0:0] o_vl_rx_1_rxld_overflow_l1_clr
    ,input  [0:0] i_vl_rx_1_rxld_overflow_l1
    ,output [0:0] o_vl_rx_2_rxld_overflow_l2_clr
    ,input  [0:0] i_vl_rx_2_rxld_overflow_l2
    ,output [0:0] o_vl_rx_3_rxld_overflow_l3_clr
    ,input  [0:0] i_vl_rx_3_rxld_overflow_l3
    ,output [0:0] o_vl_rx_0_rxld_underflow_l0_clr
    ,input  [0:0] i_vl_rx_0_rxld_underflow_l0
    ,output [0:0] o_vl_rx_0_rxld_underflow_l1_clr
    ,input  [0:0] i_vl_rx_0_rxld_underflow_l1
    ,output [0:0] o_vl_rx_0_rxld_underflow_l2_clr
    ,input  [0:0] i_vl_rx_0_rxld_underflow_l2
    ,output [0:0] o_vl_rx_0_rxld_underflow_l3_clr
    ,input  [0:0] i_vl_rx_0_rxld_underflow_l3
    ,input  [0:0] i_vl_rx_0_rxld_aligned
    ,output [0:0] o_vl_rx_0_rs_fail_l0_clr
    ,input  [0:0] i_vl_rx_0_rs_fail_l0
    ,output [0:0] o_vl_rx_0_rs_fail_l1_clr
    ,input  [0:0] i_vl_rx_0_rs_fail_l1
    ,output [0:0] o_vl_rx_0_rs_fail_l2_clr
    ,input  [0:0] i_vl_rx_0_rs_fail_l2
    ,output [0:0] o_vl_rx_0_rs_fail_l3_clr
    ,input  [0:0] i_vl_rx_0_rs_fail_l3
    ,output [0:0] o_vl_rx_0_rs_found_l0_clr
    ,input  [0:0] i_vl_rx_0_rs_found_l0
    ,output [0:0] o_vl_rx_0_rs_found_l1_clr
    ,input  [0:0] i_vl_rx_0_rs_found_l1
    ,output [0:0] o_vl_rx_0_rs_found_l2_clr
    ,input  [0:0] i_vl_rx_0_rs_found_l2
    ,output [0:0] o_vl_rx_0_rs_found_l3_clr
    ,input  [0:0] i_vl_rx_0_rs_found_l3
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l0_clr
    ,input  [15:0] i_vl_rx_0_rs_fail_cnt_l0
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l1_clr
    ,input  [15:0] i_vl_rx_0_rs_fail_cnt_l1
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l2_clr
    ,input  [15:0] i_vl_rx_0_rs_fail_cnt_l2
    ,output [0:0] o_vl_rx_0_rs_fail_cnt_l3_clr
    ,input  [15:0] i_vl_rx_0_rs_fail_cnt_l3
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l0_clr
    ,input  [15:0] i_vl_rx_0_rs_err_num_cnt_l0
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l1_clr
    ,input  [15:0] i_vl_rx_0_rs_err_num_cnt_l1
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l2_clr
    ,input  [15:0] i_vl_rx_0_rs_err_num_cnt_l2
    ,output [0:0] o_vl_rx_0_rs_err_num_cnt_l3_clr
    ,input  [15:0] i_vl_rx_0_rs_err_num_cnt_l3
    ,output [0:0] o_csr_manchest_en
    ,output [0:0] o_csr_pol_adj_en
    ,output [0:0] o_csr_pol_cont_adj
    ,output [0:0] o_csr_pol_ow_l0
    ,output [0:0] o_csr_pol_ow_l1
    ,output [0:0] o_csr_pol_ow_l2
    ,output [0:0] o_csr_pol_ow_l3
    ,output [0:0] o_csr_pol_ow_val_l0
    ,output [0:0] o_csr_pol_ow_val_l1
    ,output [0:0] o_csr_pol_ow_val_l2
    ,output [0:0] o_csr_pol_ow_val_l3
    ,input  [0:0] i_vl_rx_0_rxpol_done_l0
    ,input  [0:0] i_vl_rx_1_rxpol_done_l1
    ,input  [0:0] i_vl_rx_2_rxpol_done_l2
    ,input  [0:0] i_vl_rx_3_rxpol_done_l3
    ,input  [0:0] i_vl_rx_0_rxpol_status_l0
    ,input  [0:0] i_vl_rx_1_rxpol_status_l1
    ,input  [0:0] i_vl_rx_2_rxpol_status_l2
    ,input  [0:0] i_vl_rx_3_rxpol_status_l3
    ,output [0:0] o_csr_speed_sel_ow
    ,output [0:0] o_csr_speed_sel
    ,output [13:0] o_csr_mci_addr
    ,output [31:0] o_csr_mci_wdata
    ,output [0:0] o_vl_rx_0_mci_val
    ,output [0:0] o_vl_rx_0_mci_rdwn
    ,output [3:0] o_csr_mci_be
    ,input  [0:0] i_vl_rx_0_mci_ack
    ,input  [0:0] i_csr_mci_intr
    ,input  [31:0] i_csr_mci_rdata
    ,output [0:0] o_vl_rx_0_mci_owner


);

wire [0:0] c_csr_comma_aligned_l0;
wire [0:0] c_csr_comma_aligned_l1;
wire [0:0] c_csr_comma_aligned_l2;
wire [0:0] c_csr_comma_aligned_l3;
wire [0:0] c_csr_disp_err_l0_clr;
wire [0:0] c_csr_disp_err_l0;
wire [0:0] c_csr_disp_err_l1_clr;
wire [0:0] c_csr_disp_err_l1;
wire [0:0] c_csr_disp_err_l2_clr;
wire [0:0] c_csr_disp_err_l2;
wire [0:0] c_csr_disp_err_l3_clr;
wire [0:0] c_csr_disp_err_l3;
wire [0:0] c_csr_rxld_overflow_l0_clr;
wire [0:0] c_csr_rxld_overflow_l0;
wire [0:0] c_csr_rxld_overflow_l1_clr;
wire [0:0] c_csr_rxld_overflow_l1;
wire [0:0] c_csr_rxld_overflow_l2_clr;
wire [0:0] c_csr_rxld_overflow_l2;
wire [0:0] c_csr_rxld_overflow_l3_clr;
wire [0:0] c_csr_rxld_overflow_l3;
wire [0:0] c_csr_rxld_underflow_l0_clr;
wire [0:0] c_csr_rxld_underflow_l0;
wire [0:0] c_csr_rxld_underflow_l1_clr;
wire [0:0] c_csr_rxld_underflow_l1;
wire [0:0] c_csr_rxld_underflow_l2_clr;
wire [0:0] c_csr_rxld_underflow_l2;
wire [0:0] c_csr_rxld_underflow_l3_clr;
wire [0:0] c_csr_rxld_underflow_l3;
wire [0:0] c_csr_rxld_aligned;
wire [0:0] c_csr_rs_fail_l0_clr;
wire [0:0] c_csr_rs_fail_l0;
wire [0:0] c_csr_rs_fail_l1_clr;
wire [0:0] c_csr_rs_fail_l1;
wire [0:0] c_csr_rs_fail_l2_clr;
wire [0:0] c_csr_rs_fail_l2;
wire [0:0] c_csr_rs_fail_l3_clr;
wire [0:0] c_csr_rs_fail_l3;
wire [0:0] c_csr_rs_found_l0_clr;
wire [0:0] c_csr_rs_found_l0;
wire [0:0] c_csr_rs_found_l1_clr;
wire [0:0] c_csr_rs_found_l1;
wire [0:0] c_csr_rs_found_l2_clr;
wire [0:0] c_csr_rs_found_l2;
wire [0:0] c_csr_rs_found_l3_clr;
wire [0:0] c_csr_rs_found_l3;
wire [0:0] c_csr_rs_fail_cnt_l0_clr;
wire [15:0] c_csr_rs_fail_cnt_l0;
wire [0:0] c_csr_rs_fail_cnt_l1_clr;
wire [15:0] c_csr_rs_fail_cnt_l1;
wire [0:0] c_csr_rs_fail_cnt_l2_clr;
wire [15:0] c_csr_rs_fail_cnt_l2;
wire [0:0] c_csr_rs_fail_cnt_l3_clr;
wire [15:0] c_csr_rs_fail_cnt_l3;
wire [0:0] c_csr_rs_err_num_cnt_l0_clr;
wire [15:0] c_csr_rs_err_num_cnt_l0;
wire [0:0] c_csr_rs_err_num_cnt_l1_clr;
wire [15:0] c_csr_rs_err_num_cnt_l1;
wire [0:0] c_csr_rs_err_num_cnt_l2_clr;
wire [15:0] c_csr_rs_err_num_cnt_l2;
wire [0:0] c_csr_rs_err_num_cnt_l3_clr;
wire [15:0] c_csr_rs_err_num_cnt_l3;
wire [0:0] c_csr_rxpol_done_l0;
wire [0:0] c_csr_rxpol_done_l1;
wire [0:0] c_csr_rxpol_done_l2;
wire [0:0] c_csr_rxpol_done_l3;
wire [0:0] c_csr_rxpol_status_l0;
wire [0:0] c_csr_rxpol_status_l1;
wire [0:0] c_csr_rxpol_status_l2;
wire [0:0] c_csr_rxpol_status_l3;
wire [0:0] c_csr_mci_val;
wire [0:0] c_csr_mci_rdwn;
wire [0:0] c_csr_mci_ack;
wire [0:0] c_csr_mci_owner;


REG #(
    .AWIDTH (AWIDTH),
    .DWIDTH (DWIDTH)
) reg_inst (
    .i_cfg_clk(i_cfg_clk)
    ,.i_cfg_rst_n(i_cfg_rst_n)
    ,.i_cfg_addr    (i_cfg_addr    )
    ,.i_cfg_wr_en   (i_cfg_wr_en   )
    ,.i_cfg_wr_data (i_cfg_wr_data )
    ,.i_cfg_rd_en   (i_cfg_rd_en   )
    ,.o_cfg_rd_data (o_cfg_rd_data )
    ,.o_soft_pcs_rst(o_csr_soft_pcs_rst)
    ,.o_soft_tx_rst(o_csr_soft_tx_rst)
    ,.o_soft_rx_rst(o_csr_soft_rx_rst)
    ,.o_rw_scratch(o_csr_rw_scratch)
    ,.o_tx_x1_mode_en(o_csr_tx_x1_mode_en)
    ,.o_rx_x1_mode_en(o_csr_rx_x1_mode_en)
    ,.o_tx_rs_en(o_csr_tx_rs_en)
    ,.o_rx_rs_en(o_csr_rx_rs_en)
    ,.i_comma_aligned_l0(c_csr_comma_aligned_l0)
    ,.i_comma_aligned_l1(c_csr_comma_aligned_l1)
    ,.i_comma_aligned_l2(c_csr_comma_aligned_l2)
    ,.i_comma_aligned_l3(c_csr_comma_aligned_l3)
    ,.o_disp_err_l0_clr(c_csr_disp_err_l0_clr)
    ,.i_disp_err_l0(c_csr_disp_err_l0)
    ,.o_disp_err_l1_clr(c_csr_disp_err_l1_clr)
    ,.i_disp_err_l1(c_csr_disp_err_l1)
    ,.o_disp_err_l2_clr(c_csr_disp_err_l2_clr)
    ,.i_disp_err_l2(c_csr_disp_err_l2)
    ,.o_disp_err_l3_clr(c_csr_disp_err_l3_clr)
    ,.i_disp_err_l3(c_csr_disp_err_l3)
    ,.o_rxld_half_thres(o_csr_rxld_half_thres)
    ,.o_rxld_align_det_thres(o_csr_rxld_align_det_thres)
    ,.o_rxld_align_los_thres(o_csr_rxld_align_los_thres)
    ,.o_rxld_overflow_l0_clr(c_csr_rxld_overflow_l0_clr)
    ,.i_rxld_overflow_l0(c_csr_rxld_overflow_l0)
    ,.o_rxld_overflow_l1_clr(c_csr_rxld_overflow_l1_clr)
    ,.i_rxld_overflow_l1(c_csr_rxld_overflow_l1)
    ,.o_rxld_overflow_l2_clr(c_csr_rxld_overflow_l2_clr)
    ,.i_rxld_overflow_l2(c_csr_rxld_overflow_l2)
    ,.o_rxld_overflow_l3_clr(c_csr_rxld_overflow_l3_clr)
    ,.i_rxld_overflow_l3(c_csr_rxld_overflow_l3)
    ,.o_rxld_underflow_l0_clr(c_csr_rxld_underflow_l0_clr)
    ,.i_rxld_underflow_l0(c_csr_rxld_underflow_l0)
    ,.o_rxld_underflow_l1_clr(c_csr_rxld_underflow_l1_clr)
    ,.i_rxld_underflow_l1(c_csr_rxld_underflow_l1)
    ,.o_rxld_underflow_l2_clr(c_csr_rxld_underflow_l2_clr)
    ,.i_rxld_underflow_l2(c_csr_rxld_underflow_l2)
    ,.o_rxld_underflow_l3_clr(c_csr_rxld_underflow_l3_clr)
    ,.i_rxld_underflow_l3(c_csr_rxld_underflow_l3)
    ,.i_rxld_aligned(c_csr_rxld_aligned)
    ,.o_rs_fail_l0_clr(c_csr_rs_fail_l0_clr)
    ,.i_rs_fail_l0(c_csr_rs_fail_l0)
    ,.o_rs_fail_l1_clr(c_csr_rs_fail_l1_clr)
    ,.i_rs_fail_l1(c_csr_rs_fail_l1)
    ,.o_rs_fail_l2_clr(c_csr_rs_fail_l2_clr)
    ,.i_rs_fail_l2(c_csr_rs_fail_l2)
    ,.o_rs_fail_l3_clr(c_csr_rs_fail_l3_clr)
    ,.i_rs_fail_l3(c_csr_rs_fail_l3)
    ,.o_rs_found_l0_clr(c_csr_rs_found_l0_clr)
    ,.i_rs_found_l0(c_csr_rs_found_l0)
    ,.o_rs_found_l1_clr(c_csr_rs_found_l1_clr)
    ,.i_rs_found_l1(c_csr_rs_found_l1)
    ,.o_rs_found_l2_clr(c_csr_rs_found_l2_clr)
    ,.i_rs_found_l2(c_csr_rs_found_l2)
    ,.o_rs_found_l3_clr(c_csr_rs_found_l3_clr)
    ,.i_rs_found_l3(c_csr_rs_found_l3)
    ,.o_rs_fail_cnt_l0_clr(c_csr_rs_fail_cnt_l0_clr)
    ,.i_rs_fail_cnt_l0(c_csr_rs_fail_cnt_l0)
    ,.o_rs_fail_cnt_l1_clr(c_csr_rs_fail_cnt_l1_clr)
    ,.i_rs_fail_cnt_l1(c_csr_rs_fail_cnt_l1)
    ,.o_rs_fail_cnt_l2_clr(c_csr_rs_fail_cnt_l2_clr)
    ,.i_rs_fail_cnt_l2(c_csr_rs_fail_cnt_l2)
    ,.o_rs_fail_cnt_l3_clr(c_csr_rs_fail_cnt_l3_clr)
    ,.i_rs_fail_cnt_l3(c_csr_rs_fail_cnt_l3)
    ,.o_rs_err_num_cnt_l0_clr(c_csr_rs_err_num_cnt_l0_clr)
    ,.i_rs_err_num_cnt_l0(c_csr_rs_err_num_cnt_l0)
    ,.o_rs_err_num_cnt_l1_clr(c_csr_rs_err_num_cnt_l1_clr)
    ,.i_rs_err_num_cnt_l1(c_csr_rs_err_num_cnt_l1)
    ,.o_rs_err_num_cnt_l2_clr(c_csr_rs_err_num_cnt_l2_clr)
    ,.i_rs_err_num_cnt_l2(c_csr_rs_err_num_cnt_l2)
    ,.o_rs_err_num_cnt_l3_clr(c_csr_rs_err_num_cnt_l3_clr)
    ,.i_rs_err_num_cnt_l3(c_csr_rs_err_num_cnt_l3)
    ,.o_manchest_en(o_csr_manchest_en)
    ,.o_pol_adj_en(o_csr_pol_adj_en)
    ,.o_pol_cont_adj(o_csr_pol_cont_adj)
    ,.o_pol_ow_l0(o_csr_pol_ow_l0)
    ,.o_pol_ow_l1(o_csr_pol_ow_l1)
    ,.o_pol_ow_l2(o_csr_pol_ow_l2)
    ,.o_pol_ow_l3(o_csr_pol_ow_l3)
    ,.o_pol_ow_val_l0(o_csr_pol_ow_val_l0)
    ,.o_pol_ow_val_l1(o_csr_pol_ow_val_l1)
    ,.o_pol_ow_val_l2(o_csr_pol_ow_val_l2)
    ,.o_pol_ow_val_l3(o_csr_pol_ow_val_l3)
    ,.i_rxpol_done_l0(c_csr_rxpol_done_l0)
    ,.i_rxpol_done_l1(c_csr_rxpol_done_l1)
    ,.i_rxpol_done_l2(c_csr_rxpol_done_l2)
    ,.i_rxpol_done_l3(c_csr_rxpol_done_l3)
    ,.i_rxpol_status_l0(c_csr_rxpol_status_l0)
    ,.i_rxpol_status_l1(c_csr_rxpol_status_l1)
    ,.i_rxpol_status_l2(c_csr_rxpol_status_l2)
    ,.i_rxpol_status_l3(c_csr_rxpol_status_l3)
    ,.o_speed_sel_ow(o_csr_speed_sel_ow)
    ,.o_speed_sel(o_csr_speed_sel)
    ,.o_mci_addr(o_csr_mci_addr)
    ,.o_mci_wdata(o_csr_mci_wdata)
    ,.o_mci_val(c_csr_mci_val)
    ,.o_mci_rdwn(c_csr_mci_rdwn)
    ,.o_mci_be(o_csr_mci_be)
    ,.i_mci_ack(c_csr_mci_ack)
    ,.i_mci_intr(i_csr_mci_intr)
    ,.i_mci_rdata(i_csr_mci_rdata)
    ,.o_mci_owner(c_csr_mci_owner)

);


CDC cdc_inst(
    .i_cfg_clk(i_cfg_clk)
    ,.i_cfg_rst_n(i_cfg_rst_n)
    ,.i_vl_rx_1_clk(i_vl_rx_1_clk)
    ,.i_vl_rx_1_rst_n(i_vl_rx_1_rst_n)

    ,.i_vl_rx_3_clk(i_vl_rx_3_clk)
    ,.i_vl_rx_3_rst_n(i_vl_rx_3_rst_n)

    ,.i_vl_rx_0_clk(i_vl_rx_0_clk)
    ,.i_vl_rx_0_rst_n(i_vl_rx_0_rst_n)

    ,.i_vl_rx_2_clk(i_vl_rx_2_clk)
    ,.i_vl_rx_2_rst_n(i_vl_rx_2_rst_n)

    ,.i_vl_rx_0_comma_aligned_l0(i_vl_rx_0_comma_aligned_l0)
    ,.o_csr_comma_aligned_l0(c_csr_comma_aligned_l0)

    ,.i_vl_rx_1_comma_aligned_l1(i_vl_rx_1_comma_aligned_l1)
    ,.o_csr_comma_aligned_l1(c_csr_comma_aligned_l1)

    ,.i_vl_rx_2_comma_aligned_l2(i_vl_rx_2_comma_aligned_l2)
    ,.o_csr_comma_aligned_l2(c_csr_comma_aligned_l2)

    ,.i_vl_rx_3_comma_aligned_l3(i_vl_rx_3_comma_aligned_l3)
    ,.o_csr_comma_aligned_l3(c_csr_comma_aligned_l3)

    ,.i_csr_disp_err_l0_clr(c_csr_disp_err_l0_clr)
    ,.o_vl_rx_0_disp_err_l0_clr(o_vl_rx_0_disp_err_l0_clr)

    ,.i_vl_rx_0_disp_err_l0(i_vl_rx_0_disp_err_l0)
    ,.o_csr_disp_err_l0(c_csr_disp_err_l0)

    ,.i_csr_disp_err_l1_clr(c_csr_disp_err_l1_clr)
    ,.o_vl_rx_1_disp_err_l1_clr(o_vl_rx_1_disp_err_l1_clr)

    ,.i_vl_rx_1_disp_err_l1(i_vl_rx_1_disp_err_l1)
    ,.o_csr_disp_err_l1(c_csr_disp_err_l1)

    ,.i_csr_disp_err_l2_clr(c_csr_disp_err_l2_clr)
    ,.o_vl_rx_2_disp_err_l2_clr(o_vl_rx_2_disp_err_l2_clr)

    ,.i_vl_rx_2_disp_err_l2(i_vl_rx_2_disp_err_l2)
    ,.o_csr_disp_err_l2(c_csr_disp_err_l2)

    ,.i_csr_disp_err_l3_clr(c_csr_disp_err_l3_clr)
    ,.o_vl_rx_3_disp_err_l3_clr(o_vl_rx_3_disp_err_l3_clr)

    ,.i_vl_rx_3_disp_err_l3(i_vl_rx_3_disp_err_l3)
    ,.o_csr_disp_err_l3(c_csr_disp_err_l3)

    ,.i_csr_rxld_overflow_l0_clr(c_csr_rxld_overflow_l0_clr)
    ,.o_vl_rx_0_rxld_overflow_l0_clr(o_vl_rx_0_rxld_overflow_l0_clr)

    ,.i_vl_rx_0_rxld_overflow_l0(i_vl_rx_0_rxld_overflow_l0)
    ,.o_csr_rxld_overflow_l0(c_csr_rxld_overflow_l0)

    ,.i_csr_rxld_overflow_l1_clr(c_csr_rxld_overflow_l1_clr)
    ,.o_vl_rx_1_rxld_overflow_l1_clr(o_vl_rx_1_rxld_overflow_l1_clr)

    ,.i_vl_rx_1_rxld_overflow_l1(i_vl_rx_1_rxld_overflow_l1)
    ,.o_csr_rxld_overflow_l1(c_csr_rxld_overflow_l1)

    ,.i_csr_rxld_overflow_l2_clr(c_csr_rxld_overflow_l2_clr)
    ,.o_vl_rx_2_rxld_overflow_l2_clr(o_vl_rx_2_rxld_overflow_l2_clr)

    ,.i_vl_rx_2_rxld_overflow_l2(i_vl_rx_2_rxld_overflow_l2)
    ,.o_csr_rxld_overflow_l2(c_csr_rxld_overflow_l2)

    ,.i_csr_rxld_overflow_l3_clr(c_csr_rxld_overflow_l3_clr)
    ,.o_vl_rx_3_rxld_overflow_l3_clr(o_vl_rx_3_rxld_overflow_l3_clr)

    ,.i_vl_rx_3_rxld_overflow_l3(i_vl_rx_3_rxld_overflow_l3)
    ,.o_csr_rxld_overflow_l3(c_csr_rxld_overflow_l3)

    ,.i_csr_rxld_underflow_l0_clr(c_csr_rxld_underflow_l0_clr)
    ,.o_vl_rx_0_rxld_underflow_l0_clr(o_vl_rx_0_rxld_underflow_l0_clr)

    ,.i_vl_rx_0_rxld_underflow_l0(i_vl_rx_0_rxld_underflow_l0)
    ,.o_csr_rxld_underflow_l0(c_csr_rxld_underflow_l0)

    ,.i_csr_rxld_underflow_l1_clr(c_csr_rxld_underflow_l1_clr)
    ,.o_vl_rx_0_rxld_underflow_l1_clr(o_vl_rx_0_rxld_underflow_l1_clr)

    ,.i_vl_rx_0_rxld_underflow_l1(i_vl_rx_0_rxld_underflow_l1)
    ,.o_csr_rxld_underflow_l1(c_csr_rxld_underflow_l1)

    ,.i_csr_rxld_underflow_l2_clr(c_csr_rxld_underflow_l2_clr)
    ,.o_vl_rx_0_rxld_underflow_l2_clr(o_vl_rx_0_rxld_underflow_l2_clr)

    ,.i_vl_rx_0_rxld_underflow_l2(i_vl_rx_0_rxld_underflow_l2)
    ,.o_csr_rxld_underflow_l2(c_csr_rxld_underflow_l2)

    ,.i_csr_rxld_underflow_l3_clr(c_csr_rxld_underflow_l3_clr)
    ,.o_vl_rx_0_rxld_underflow_l3_clr(o_vl_rx_0_rxld_underflow_l3_clr)

    ,.i_vl_rx_0_rxld_underflow_l3(i_vl_rx_0_rxld_underflow_l3)
    ,.o_csr_rxld_underflow_l3(c_csr_rxld_underflow_l3)

    ,.i_vl_rx_0_rxld_aligned(i_vl_rx_0_rxld_aligned)
    ,.o_csr_rxld_aligned(c_csr_rxld_aligned)

    ,.i_csr_rs_fail_l0_clr(c_csr_rs_fail_l0_clr)
    ,.o_vl_rx_0_rs_fail_l0_clr(o_vl_rx_0_rs_fail_l0_clr)

    ,.i_vl_rx_0_rs_fail_l0(i_vl_rx_0_rs_fail_l0)
    ,.o_csr_rs_fail_l0(c_csr_rs_fail_l0)

    ,.i_csr_rs_fail_l1_clr(c_csr_rs_fail_l1_clr)
    ,.o_vl_rx_0_rs_fail_l1_clr(o_vl_rx_0_rs_fail_l1_clr)

    ,.i_vl_rx_0_rs_fail_l1(i_vl_rx_0_rs_fail_l1)
    ,.o_csr_rs_fail_l1(c_csr_rs_fail_l1)

    ,.i_csr_rs_fail_l2_clr(c_csr_rs_fail_l2_clr)
    ,.o_vl_rx_0_rs_fail_l2_clr(o_vl_rx_0_rs_fail_l2_clr)

    ,.i_vl_rx_0_rs_fail_l2(i_vl_rx_0_rs_fail_l2)
    ,.o_csr_rs_fail_l2(c_csr_rs_fail_l2)

    ,.i_csr_rs_fail_l3_clr(c_csr_rs_fail_l3_clr)
    ,.o_vl_rx_0_rs_fail_l3_clr(o_vl_rx_0_rs_fail_l3_clr)

    ,.i_vl_rx_0_rs_fail_l3(i_vl_rx_0_rs_fail_l3)
    ,.o_csr_rs_fail_l3(c_csr_rs_fail_l3)

    ,.i_csr_rs_found_l0_clr(c_csr_rs_found_l0_clr)
    ,.o_vl_rx_0_rs_found_l0_clr(o_vl_rx_0_rs_found_l0_clr)

    ,.i_vl_rx_0_rs_found_l0(i_vl_rx_0_rs_found_l0)
    ,.o_csr_rs_found_l0(c_csr_rs_found_l0)

    ,.i_csr_rs_found_l1_clr(c_csr_rs_found_l1_clr)
    ,.o_vl_rx_0_rs_found_l1_clr(o_vl_rx_0_rs_found_l1_clr)

    ,.i_vl_rx_0_rs_found_l1(i_vl_rx_0_rs_found_l1)
    ,.o_csr_rs_found_l1(c_csr_rs_found_l1)

    ,.i_csr_rs_found_l2_clr(c_csr_rs_found_l2_clr)
    ,.o_vl_rx_0_rs_found_l2_clr(o_vl_rx_0_rs_found_l2_clr)

    ,.i_vl_rx_0_rs_found_l2(i_vl_rx_0_rs_found_l2)
    ,.o_csr_rs_found_l2(c_csr_rs_found_l2)

    ,.i_csr_rs_found_l3_clr(c_csr_rs_found_l3_clr)
    ,.o_vl_rx_0_rs_found_l3_clr(o_vl_rx_0_rs_found_l3_clr)

    ,.i_vl_rx_0_rs_found_l3(i_vl_rx_0_rs_found_l3)
    ,.o_csr_rs_found_l3(c_csr_rs_found_l3)

    ,.i_csr_rs_fail_cnt_l0_clr(c_csr_rs_fail_cnt_l0_clr)
    ,.o_vl_rx_0_rs_fail_cnt_l0_clr(o_vl_rx_0_rs_fail_cnt_l0_clr)

    ,.i_vl_rx_0_rs_fail_cnt_l0(i_vl_rx_0_rs_fail_cnt_l0)
    ,.o_csr_rs_fail_cnt_l0(c_csr_rs_fail_cnt_l0)

    ,.i_csr_rs_fail_cnt_l1_clr(c_csr_rs_fail_cnt_l1_clr)
    ,.o_vl_rx_0_rs_fail_cnt_l1_clr(o_vl_rx_0_rs_fail_cnt_l1_clr)

    ,.i_vl_rx_0_rs_fail_cnt_l1(i_vl_rx_0_rs_fail_cnt_l1)
    ,.o_csr_rs_fail_cnt_l1(c_csr_rs_fail_cnt_l1)

    ,.i_csr_rs_fail_cnt_l2_clr(c_csr_rs_fail_cnt_l2_clr)
    ,.o_vl_rx_0_rs_fail_cnt_l2_clr(o_vl_rx_0_rs_fail_cnt_l2_clr)

    ,.i_vl_rx_0_rs_fail_cnt_l2(i_vl_rx_0_rs_fail_cnt_l2)
    ,.o_csr_rs_fail_cnt_l2(c_csr_rs_fail_cnt_l2)

    ,.i_csr_rs_fail_cnt_l3_clr(c_csr_rs_fail_cnt_l3_clr)
    ,.o_vl_rx_0_rs_fail_cnt_l3_clr(o_vl_rx_0_rs_fail_cnt_l3_clr)

    ,.i_vl_rx_0_rs_fail_cnt_l3(i_vl_rx_0_rs_fail_cnt_l3)
    ,.o_csr_rs_fail_cnt_l3(c_csr_rs_fail_cnt_l3)

    ,.i_csr_rs_err_num_cnt_l0_clr(c_csr_rs_err_num_cnt_l0_clr)
    ,.o_vl_rx_0_rs_err_num_cnt_l0_clr(o_vl_rx_0_rs_err_num_cnt_l0_clr)

    ,.i_vl_rx_0_rs_err_num_cnt_l0(i_vl_rx_0_rs_err_num_cnt_l0)
    ,.o_csr_rs_err_num_cnt_l0(c_csr_rs_err_num_cnt_l0)

    ,.i_csr_rs_err_num_cnt_l1_clr(c_csr_rs_err_num_cnt_l1_clr)
    ,.o_vl_rx_0_rs_err_num_cnt_l1_clr(o_vl_rx_0_rs_err_num_cnt_l1_clr)

    ,.i_vl_rx_0_rs_err_num_cnt_l1(i_vl_rx_0_rs_err_num_cnt_l1)
    ,.o_csr_rs_err_num_cnt_l1(c_csr_rs_err_num_cnt_l1)

    ,.i_csr_rs_err_num_cnt_l2_clr(c_csr_rs_err_num_cnt_l2_clr)
    ,.o_vl_rx_0_rs_err_num_cnt_l2_clr(o_vl_rx_0_rs_err_num_cnt_l2_clr)

    ,.i_vl_rx_0_rs_err_num_cnt_l2(i_vl_rx_0_rs_err_num_cnt_l2)
    ,.o_csr_rs_err_num_cnt_l2(c_csr_rs_err_num_cnt_l2)

    ,.i_csr_rs_err_num_cnt_l3_clr(c_csr_rs_err_num_cnt_l3_clr)
    ,.o_vl_rx_0_rs_err_num_cnt_l3_clr(o_vl_rx_0_rs_err_num_cnt_l3_clr)

    ,.i_vl_rx_0_rs_err_num_cnt_l3(i_vl_rx_0_rs_err_num_cnt_l3)
    ,.o_csr_rs_err_num_cnt_l3(c_csr_rs_err_num_cnt_l3)

    ,.i_vl_rx_0_rxpol_done_l0(i_vl_rx_0_rxpol_done_l0)
    ,.o_csr_rxpol_done_l0(c_csr_rxpol_done_l0)

    ,.i_vl_rx_1_rxpol_done_l1(i_vl_rx_1_rxpol_done_l1)
    ,.o_csr_rxpol_done_l1(c_csr_rxpol_done_l1)

    ,.i_vl_rx_2_rxpol_done_l2(i_vl_rx_2_rxpol_done_l2)
    ,.o_csr_rxpol_done_l2(c_csr_rxpol_done_l2)

    ,.i_vl_rx_3_rxpol_done_l3(i_vl_rx_3_rxpol_done_l3)
    ,.o_csr_rxpol_done_l3(c_csr_rxpol_done_l3)

    ,.i_vl_rx_0_rxpol_status_l0(i_vl_rx_0_rxpol_status_l0)
    ,.o_csr_rxpol_status_l0(c_csr_rxpol_status_l0)

    ,.i_vl_rx_1_rxpol_status_l1(i_vl_rx_1_rxpol_status_l1)
    ,.o_csr_rxpol_status_l1(c_csr_rxpol_status_l1)

    ,.i_vl_rx_2_rxpol_status_l2(i_vl_rx_2_rxpol_status_l2)
    ,.o_csr_rxpol_status_l2(c_csr_rxpol_status_l2)

    ,.i_vl_rx_3_rxpol_status_l3(i_vl_rx_3_rxpol_status_l3)
    ,.o_csr_rxpol_status_l3(c_csr_rxpol_status_l3)

    ,.i_csr_mci_val(c_csr_mci_val)
    ,.o_vl_rx_0_mci_val(o_vl_rx_0_mci_val)

    ,.i_csr_mci_rdwn(c_csr_mci_rdwn)
    ,.o_vl_rx_0_mci_rdwn(o_vl_rx_0_mci_rdwn)

    ,.i_vl_rx_0_mci_ack(i_vl_rx_0_mci_ack)
    ,.o_csr_mci_ack(c_csr_mci_ack)

    ,.i_csr_mci_owner(c_csr_mci_owner)
    ,.o_vl_rx_0_mci_owner(o_vl_rx_0_mci_owner)


);
    
    
endmodule
    
    
    
