// Generated by Reed Solomon 18.0 [Altera, IP Toolbench 1.3.0 Build 614]
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2019 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.

module RS_ENC_LANE_QUATUS (
	clk,
	reset,
	rsin,
	sink_val,
	sink_sop,
	sink_eop,
	source_ena,
	rsout,
	sink_ena,
	source_val,
	source_sop,
	source_eop);

	input		clk;
	input		reset;
	input	[8:1]	rsin;
	input		sink_val;
	input		sink_sop;
	input		sink_eop;
	input		source_ena;
	output	[8:1]	rsout;
	output		sink_ena;
	output		source_val;
	output		source_sop;
	output		source_eop;
endmodule
